spring.application.name=configserver

#Config Server
#Config File URL
spring.cloud.config.server.git.uri=https://github.com/Rohit6458/Config_Files
# Username and Password (If your config files are private)
# If your config files are inside folders
spring.cloud.config.server.git.search-paths=global,orderservice
# Load the config files on startup into the config server cache
spring.cloud.config.server.git.clone-on-start=true
# Branch to read configuration from
spring.cloud.config.server.git.default-label=main

#Help to debug Config server cache loading
logging.level.org.springframework.cloud.config.server=DEBUG
logging.level.org.eclipse.jgit=DEBUG

#Actuator
management.endpoints.web.exposure.include=*
