spring.application.name=order-service
server.port=8082

#Profile
spring.profiles.active=dev

#Config Client Settings (optional:configserver help if config server is down then it will use local properties)
spring.config.import=optional:configserver:http://localhost:8080
message=Welcome to the local order service

#Actuator refresh API
management.endpoints.web.exposure.include=refresh
